version: '3.7'

services:
  web:
    container_name: react-app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:3000
    volumes:
      - '.:/app'