name: Build Docker React App

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm ci

      - name: Lint SCSS and JavaScript/TypeScript
        run: npm run lint

      - name: Run JavaScript Tests
        run: npm run test

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: empee333/build-pipeline-react
      
      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Slack notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#exploring-cohort-notifications'
        if: always()