name: Create Artifact and Release

on:
  push:
    tags:
    - "v*.*.*"
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Create release artifact
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'react-pipeline.zip'
          path: './dist'

    deploy:
      runs-on: ubuntu-latest
      name: 'Deploy to Netlify'
      steps:
        - uses: jsmrcaga/action-netlify-deploy@v1.1.0
          with:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
            NETLIFY_DEPLOY_TO_PROD: true
