name: Create Artifact and Release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Create release artifact
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'react-pipeline.zip'
          path: './dist'
